# Generated by Django 4.2.5 on 2023-09-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslık', models.CharField(max_length=50)),
                ('acıklama', models.TextField()),
                ('resim', models.ImageField(default='kurs_resimleri', upload_to='')),
                ('tarih', models.DateField()),
                ('aktifKurs', models.BooleanField(default=False)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
