# Generated by Django 4.2.5 on 2023-09-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0002_kategori_kurs_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='baslık',
            new_name='baslik',
        ),
    ]
